import {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse} from '@simplewebauthn/server';
export async function setupPasskeys(sql){
 await sql`CREATE TABLE IF NOT EXISTS money_passkeys (id text PRIMARY KEY,user_id uuid NOT NULL REFERENCES money_users(id) ON DELETE CASCADE,public_key bytea NOT NULL,counter bigint NOT NULL,transports jsonb NOT NULL DEFAULT '[]',name text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`;
 await sql`CREATE TABLE IF NOT EXISTS money_passkey_challenges (id text PRIMARY KEY,challenge text NOT NULL,kind text NOT NULL,user_id uuid,session_hash text,expires_at timestamptz NOT NULL)`;
}
export function passkeyHandler({sql,origin,body,send,fail,cookie,newToken,tokenHash,verifyPassword}){
 const rpID=new URL(origin).hostname,rates=new Map();
 async function password(user,password){if(typeof password!=='string'||password.length>128)fail(400,'Введите текущий пароль.');const [row]=await sql`SELECT password_hash FROM money_users WHERE id=${user.id}`;if(!row||!await verifyPassword(password,row.password_hash))fail(403,'Неверный пароль.');}
 async function challenge(options,kind,session){const id=newToken();await sql`DELETE FROM money_passkey_challenges WHERE expires_at<now()`;await sql`INSERT INTO money_passkey_challenges(id,challenge,kind,user_id,session_hash,expires_at) VALUES(${tokenHash(id)},${options.challenge},${kind},${session?.user.id||null},${session?.hash||null},now()+interval '5 minutes')`;return {options,challengeId:id};}
 async function consume(input,kind,session){if(typeof input.challengeId!=='string'||input.challengeId.length!==64)fail(400,'Повторите подтверждение.');const [row]=await sql`DELETE FROM money_passkey_challenges WHERE id=${tokenHash(input.challengeId)} AND kind=${kind} AND expires_at>now() RETURNING *`;if(!row||kind==='register'&&(row.user_id!==session.user.id||row.session_hash!==session.hash))fail(400,'Подтверждение истекло. Повторите действие.');return row;}
 return async(req,res,path,session)=>{
 if(!path.startsWith('/api/passkeys/'))return false;
 const key=req.socket.remoteAddress;let rate=rates.get(key);if(!rate||rate.until<Date.now()){rate={count:0,until:Date.now()+900000};rates.set(key,rate);}if(++rate.count>60)fail(429,'Слишком много попыток. Повторите позже.');if(rates.size>10000)for(const [k,v]of rates)if(v.until<Date.now())rates.delete(k);
 if(path==='/api/passkeys/login-options'&&req.method==='POST'){const options=await generateAuthenticationOptions({rpID,userVerification:'required'});send(res,200,await challenge(options,'login'));return true;}
 if(path==='/api/passkeys/login-verify'&&req.method==='POST'){
 const input=await body(req),ch=await consume(input,'login');const result=await sql.begin(async tx=>{const [key]=await tx`SELECT * FROM money_passkeys WHERE id=${input.response?.id||''} FOR UPDATE`;if(!key)fail(401,'Ключ доступа не зарегистрирован. Войдите по паролю.');let v;try{v=await verifyAuthenticationResponse({response:input.response,expectedChallenge:ch.challenge,expectedOrigin:origin,expectedRPID:rpID,credential:{id:key.id,publicKey:new Uint8Array(key.public_key),counter:Number(key.counter),transports:key.transports},requireUserVerification:true});}catch{fail(401,'Подтверждение входа не прошло проверку.');}if(!v.verified)fail(401,'Вход не подтверждён.');if(input.response.response?.userHandle&&input.response.response.userHandle!==Buffer.from(key.user_id).toString('base64url'))fail(401,'Некорректный ключ аккаунта.');await tx`UPDATE money_passkeys SET counter=${v.authenticationInfo.newCounter} WHERE id=${key.id}`;const [user]=await tx`SELECT id,email,name FROM money_users WHERE id=${key.user_id}`;const token=newToken();await tx`INSERT INTO money_sessions(token_hash,user_id,expires_at) VALUES(${tokenHash(token)},${user.id},now()+interval '30 days')`;return {user,token};});cookie(res,result.token);send(res,200,{user:result.user});return true;
 }
 if(!session)fail(401,'Войдите в аккаунт.');
 if(path==='/api/passkeys/list'&&req.method==='GET'){const keys=await sql`SELECT id,name,created_at FROM money_passkeys WHERE user_id=${session.user.id} ORDER BY created_at DESC`;send(res,200,{keys});return true;}
 if(path==='/api/passkeys/register-options'&&req.method==='POST'){const input=await body(req);await password(session.user,input.password);const keys=await sql`SELECT id,transports FROM money_passkeys WHERE user_id=${session.user.id}`;if(keys.length>=10)fail(400,'Можно добавить до 10 ключей.');const options=await generateRegistrationOptions({rpName:'Баланс',rpID,userID:Buffer.from(session.user.id),userName:session.user.email,attestationType:'none',authenticatorSelection:{residentKey:'required',userVerification:'required',authenticatorAttachment:'platform'},excludeCredentials:keys.map(k=>({id:k.id,transports:k.transports}))});send(res,200,await challenge(options,'register',session));return true;}
 if(path==='/api/passkeys/register-verify'&&req.method==='POST'){const input=await body(req),ch=await consume(input,'register',session);let v;try{v=await verifyRegistrationResponse({response:input.response,expectedChallenge:ch.challenge,expectedOrigin:origin,expectedRPID:rpID,requireUserVerification:true});}catch{fail(400,'Ключ доступа не прошёл проверку.');}if(!v.verified)fail(400,'Регистрация не подтверждена.');const c=v.registrationInfo.credential,name=typeof input.name==='string'&&input.name.trim()?input.name.trim().slice(0,100):'Мой телефон';await sql`INSERT INTO money_passkeys(id,user_id,public_key,counter,transports,name) VALUES(${c.id},${session.user.id},${Buffer.from(c.publicKey)},${c.counter},${sql.json(c.transports||[])},${name}) ON CONFLICT(id) DO NOTHING`;send(res,200,{ok:true});return true;}
 if(path==='/api/passkeys/remove'&&req.method==='POST'){const input=await body(req);await password(session.user,input.password);if(typeof input.id!=='string'||input.id.length>2000)fail(400,'Некорректный ключ.');await sql`DELETE FROM money_passkeys WHERE user_id=${session.user.id} AND id=${input.id}`;send(res,200,{ok:true});return true;}
 fail(404,'Не найдено.');
 };
}
